version: "3.4"

services: 
  web: 
    image: node:lts-alpine
    working_dir: /usr/app
    stdin_open: true
    command: yarn
    command: yarn start
    ports:
    - "3000:3000"
    volumes: 
    - "./:/usr/app"
